name: Auto Approve

on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  auto-approve:
    if: github.event.pull_request.user.login == 'Naresh' || github.event.pull_request.user.login == 'naresh'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Auto approve PR from repo owner
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
